[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.100"
itertools = "0.14.0"
regex = "1.12.2"

[[bin]]
name = "day_1"
path = "1/day_1.rs"
